version: "2"

services:
  # Frontend (Next.js app)
  frontend:
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=${MONGODB_URL}
    build: . # Build the image from the current directory (Dockerfile needed later)
    ports:
      - "3000:3000" # Map container port 3000 to your local machine's port 3000
    develop:
      # we specify the files to watch for changes
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
          # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: .
          target: /app
          action: sync

  # MongoDB database
  mongo:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 4
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongo"
    ports:
      - "27018:27018"
    restart: unless-stopped
    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test:
        [
          "CMD",
          "mongo",
          "admin",
          "--port",
          "27018",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
